[project]
name = "lookupCacheAPI"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">= 3.14"
dependencies = [
    "litestar[standard,sqlalchemy]",
    "aiosqlite",
]
[dependency-groups]
dev = [
    "pytest",
]
